### ISSUE TITLE
Dev known issues tracker

### ISSUE THREAD

**Issue by DevilXD** [DevilXD/TwitchDropsMiner#73]
This is more or less like a public TODO list for me, to unload the need of having to remember all of this. Will get on those once I find enough free time.

- [x] Gracefully handle `_brotli` ImportError by informing the user they'll have to install the redis:
```py
Traceback (most recent call last):
  File "main.py", line 39, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "twitch.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "gui.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\undetected_chromedriver__init.py__", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\undetected_chromedriver\webdriver.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\inspect.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\har.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\thirdparty\mitmproxy\http.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\thirdparty\mitmproxy\net\http__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
File "seleniumwire\thirdparty\mitmproxy\net\http\http1__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "brotli.py", line 8, in <module>
ImportError: DLL load failed while importing _brotli: The specified module could not be found.
```
Refs:
https://stackoverflow.com/questions/63494005/error-when-importing-dash-importerror-dll-load-failed-while-importing-brotli
https://github.com/google/brotli/issues/782
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

Handled via: https://github.com/DevilXD/TwitchDropsMiner/commit/4ae68b7d2318e17f5558828932d23ef3b96bc699

***

- [x] Handle missing certificate on non-dev stations by including it as data per dev's solution:
```py
Traceback (most recent call last):
  File "main.py", line 179, in <module>
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "twitch.py", line 351, in run
  File "twitch.py", line 370, in _run
  File "twitch.py", line 913, in get_auth
  File "twitch.py", line 136, in validate
  File "twitch.py", line 161, in _validate
  File "twitch.py", line 107, in _login
  File "gui.py", line 506, in ask_login
  File "gui.py", line 1970, in coro_unless_closed
  File "concurrent\futures\thread.py", line 58, in run
  File "gui.py", line 497, in <lambda>
  File "seleniumwire\undetected_chromedriver\webdriver.py", line 32, in init
  File "seleniumwire\webdriver.py", line 41, in _setup_backend
  File "seleniumwire\backend.py", line 24, in create
  File "seleniumwire\server.py", line 28, in init
  File "seleniumwire\utils.py", line 159, in extract_cert_and_key
  File "pkgutil.py", line 639, in get_data
  File "PyInstaller\loader\pyimod02_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\twitch\AppData\Local\Temp\_MEI17842\seleniumwire\ca.crt'
```
Refs: 
https://github.com/wkeeling/selenium-wire/issues/402#issuecomment-1059038086

Handled via: https://github.com/DevilXD/TwitchDropsMiner/commit/d3d1624a243a96c0958972edfce1f9c99891b03b

***

- [x] Make it so that the Chrome instance starts with the HTTP proxy already set

Refs:
https://selenium-python.readthedocs.io/api.html#selenium.webdriver.common.proxy.Proxy

Handled via: https://github.com/DevilXD/TwitchDropsMiner/commit/1aa1976c1a4471465f2a3a06625352fea6e3582f
